### ISSUE TITLE
Gather information for potential online payment solutions

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-residential-parking-permits#60]
### [Chase Pay Connect](https://www.jpmorgan.com/tss/Blank/Pay_Connexion_Demo_Landing_Page__How_it_Works/1266453770751) 
- [x] [Docs](https://teams.microsoft.com/_#/files/General?threadId=19%3Ae3597e8949f8488c961b78460a886d45%40thread.skype&ctx=channel&context=Phase%2520II%252FPayments%252FChase%2520Pay%2520Connect)
- [x] Security approval
- [x] Comptroller approval
- [x] Feedback from admin users (Library, EMS)
- [ ] User test with residents?

### [Stripe](https://stripe.com/)
- [x] [Docs](https://stripe.com/docs)
- [ ] Security approval - have done preliminary but need to review again with Tarek and Jeremiah
- [ ] Comptroller approval
- [ ] Feedback from admin users (in other municipalities ?)
- [ ] User test with residents?

**Comment by amenity** [comment]
@teripennington - do you know where we might be able to get access to the Chase docs or docs for other solutions the City is looking at? It would be great to look them over before Wednesday's meeting if possible!

**Comment by johnclary** [comment]
Met with Controllers Office and Treasury today. We primarily discussed Chase Pay Connect (formerly Pay Connexion 👀) but also had productive discussion around bringing on a different provider e.g. Stripe.

My notes:

- Parks, AE use other vendors
- Note that Chase contract ends this year. RFP for new contract is already being written. May not be Chase 12 mos from now. 
- Chase payments can be simple or complex
- “Light implementation”: Go the connection pay and do it
- Complex (via “APIs”):
    - Authenticate on billing system (e.g. Knack)
    - Transfer authenticated user to pay connection
        - Save credit card info
    - Returns you to the billing system
    - Can also use Basic POSTs 
    
- Chase Pay Connect is just the online payment portal. “Payment Tech” actually transfers funds

- In payment portal > you can customize:
    -  text and instructions
    - header on page
    - Where do you want the help calls to go?
    - Do you want an email?


Fees for Chase:
    - City can cover the convenience fee or pass it to the customer.
        - Credit card is 2.5% of transaction + 30 cents. Note: Stripe is 2.9% plus 30 cents)
    - ACH (check) convenience fee is 31 cents 
    - Mark recommends not doing ACH because with credit card you get the money right away, you know everything’s right. With ACH you deal with bank holidays, delay if it turns out that the money wasn’t there, that the account number was correct, and you won’t know until the next business day. Or at least do ACH the same way you do it in person. ACH doesn’t actually go through payment tech 

Mark estimates that if we’re working Chase it could take 3 months.

If we go through Chase Pay Connect the process is:
- No security review (CTM has alreay approved)
- Treasury sets up the merchant processing accounts
- We work with Chase to config the payment flow

If we go through Stripe:
- CTM security reviews (Jeremiah and/or Taureg) < note that we did a cursory review already
- We complete a memo and a questionnaire for Treasury and wait approx two weeks have merchant accounts
- Sounds too easy?

- Mark sent Teri implementation docs for Chase and Teri will share those once she has email access again 🙄 

Other thoughts:
- I'm 100% in favor of pursuing Stripe if we're going to build the permit solution in Knack
- We need to resolve the question of if Parking Enterprise still wants to pursue permits through their Parking App Vendor [Passport](https://www.passportparking.com/)
- R.e. Chase Pay Connect, I have some doubts about our technical ability to do the fancy authenticated payment transfer with Knack, because we have limited ability to configure the app in that way.

**Comment by amenity** [comment]
From Bob Bell at Austin Public Library. (He's the one who implemented and runs the library fee collection with Chase Connexion.)

**How was it for you to set up initially and then maintain?**
- It was a long (more than year long journey), but that included various citywide functions, which may be streamlined now.  
- We had to stand up hardware and software in City DMZ, which involved CTM and CTM Security giving the blessing every step of the way, because of the potential PCI Compliance issues.    
- There were official CTM Project Management involved, which was rather onerous (from a developers/integrators point of view) at some point, but we muddled through. 
- There was Chase deployment methodologies and setup that required this CTM Project Management, and contractual agreements and integration with Finance and Treasury that were highly technical, but everyone performed well and timely for the most part.
- The tricky parts are setting up the round trip processes. We create City side transactions from authenticated users who select fines that they wish to pay, then we transfer control over to Chase, they process the credit cards without us every storing any PCI information, then Chase makes call back to our COA DMZ servers indicating taking payment for the transaction, then our side applies the transaction to our systems. The only information passed to Chase is our Patrons library card, session token, payment transaction id, and amount. 

**I noticed that the form linked to from [their demo site](https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.payconnexion.com%2Fdemo%2Findex.html&data=02%7C01%7CAmenity.Applewhite%40austintexas.gov%7Cffca7942a7c14e5431ea08d6da1b9ddb%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C636936209473442726&sdata=WEK0g7%2FKgbVRuh3Kq6iGi3UgkyyhrAdASbZkU8mGFVA%3D&reserved=0) has numerous accessibility errors. Can anything be done to remediate that?** 
- I do not know.  

**Do residents generally find it easy to use?**
- There are about $80,000.00 year payments made through it, and I have not heard major complaints from public, but there are some APL Finance reconciliation processes that can be complicated, and challenging to troubleshoot sometime, but not very frequently do we have issues.  Like, when Chase receives a Payment, but we were not successful in applying to our patrons fines.   Generally, if you setup the Procedures for handling these exceptions, front line staff can get them resolved fairly quickly. There are always people who generally want things to work they want them to, and will complain, but I get the feeling it is generally easy enough to use for them. No official, usability studies have been done, or surveys to find out. 😄 

**Are there any features or drawbacks we should be aware of?** 
- There are features that I am sure we did not take advantage of, as our initial setup was only to pay Library Fines (one single product code) and deposit this directly into our General Fund.   
- I think we should have setup additional Features, like Donations/Gifts to the library and had Finance create the necessary deposit accounts, because in order to now embark on that venture, we would have to setup another whole project and go through it all again, which makes us hesitate at the moment.

**Comment by ghost** [comment]
Decision:  Use mobile platform solution (and payment solution) for RPP unless there is a major issue.


Notes:

Decide online payment solution for knack
Connect: 2.9% + $0.30, 3 month implementation estimate, contract expiring
 Stripe: 2.9% + $0.30, all cards, no e-check, 2 month implementation estimate, ADA compliant, not locked in
 Whatever the mobile platform payment processor:  Won't have a solution until fall.  Back office solutions.
decide online payment solution for mobile pay - use company solution

needs:

back office for payments

Wallet

fees on the backend

integration requirements, easy APIs
Spanish

room for expansion

parkATX

mobile pay - pay by app on phone

maps

shows where permits are active

split RFP into sections to encourage integration

integrate with knack

enforcement: citation revenue, location of citations, license plate reader,

Tylertech solution, androids, (Talk with Siham Niseef and Robert Turner) for parking enforcement that APD uses.

Scooter data on open data portal - AWS data warehouse

Other permits:

Chauffeur permits

pedi-cabs

rides for hire

valet operators

trade permitting

validation of parking

right of way for valets
