### ISSUE TITLE
Talk to Oak Park about using Passport

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-residential-parking-permits#79]
**Objective** 
Oak Park is a Passport customer, see their app here:
[City of Oak Park, IL RPP Landing Page](https://oakpark.cmrpay.com/permits/login)

**Participants**

Oak Park:

- Will Gillespie - Manager of parking and mobility - primary passport contact

- Delia - Parking staff 

- Robert Anderson - Director of Adjudication - excused since we're not working on citations/adjuducation

DTS: Amenity, Teri

Parking: Ryan, Alyse, Joseph

**Comment by ghost** [comment]
customer since 2013, mobile pay for meters, overnight parking mobile pay
2018 permits - residential permits, passes, enforcement, unified landing page, citations
City of Austin - using mobile pay (ParkX), process of looking at residential parking permits, customers for a couple years.  
Initially, Passport was very responsive.  Did a lot of fact finding.  Very organized.  Good at tracking issues.  
Oak Park:  100 lots, wheel techs, garages, resident and non-resident.  Permitting is very complicated so Passport had to grow a lot.  
Permits for Oak Park:  lots of capabilities, works really well.
ability to wait list people - lots sold out due to demand.  Let's the wait list person know that there is an opening, gives them a short amount of time to respond and then either purchases or expires.
Customers can do their own permit purchase, village license, with automatic renewal (every 3 months).
Challenges:  strict deadline for permits.  Built a new system from scratch for Oak Park.  At time of launch, regular issues with system.  
Sent out renewal letters for quarterly expiration dates - accidentally sent to everyone instead of just the small group.  (actual letters and emails that Passport sends out).
Found out a week before launch that Safari was a problem.
Everything is a matter of time - need 2 months more!  Roll out to a smaller group to minimize would have been a better idea to find those errors.  3 months fact finding, 3 months to roll out citations and then 2 months on permits.  
Should have sent out a few hundred at a time instead of all at once.  
Did you have to revert back to old system?  No, old system didn't exist. even if we had the option, they would have only used it briefly.  Vehicle license sales - Passport wasn't ready so they created a google sheet as a work around.

**Comment by amenity** [comment]
@teripennington so speedy!!!

Have been working with Passport since 2013
- Initially related to mobile-pay for meters
- Then added passes for overnight parking
- New contract (since September 2018) using to issue residential permits, citations and adjudication, white label application for resident use

- Had another parking solution - 20 years old, 8 different databases
- We've signed on to quite a lot of services, Passport was initially very responsive and involved
- Oak Park has very complex needs - 100 lots, numerous types of regulations, etc. Passport was really responsive diving into details of system, very organized
  - Created user groups to do research on needs
  - Organized requirements documents
  - Our permit system was outside the scope of what they were prepared to accept; permits in larger/denser municipalities more complex than places they'd initially worked
  - Overall very positive experience
- Rolled out citations first, were confident going into it, but found bugs they were responsive tracking feedback but not all issues have been resolved quickly
- We had a very strict deadline for Passport bc we were phasing out systems and going sticker-less; felt very confident… since launch (1 month ago) have continued to have fairly regular issues with system not meeting needs
  - Some small & solveable but others are worrisome ("Like 'how did that happen?!'"), e.g. 
    - Send out renewal letters every quarter to permit holders so they can go online and renew. Had spoken to Passport about it at length, but emails and actual letters went out to all residents rather than just residents who needed to renew. Have been a lot of unhappy vocal residents, taking a lot of staff time. 
    - Couldn't log in to site using Safari. Anticipated that everyone was going to open on their phone, had to write last minute instructions to all customers how to download Chrome (!) 
  - The system is great, it works very well when it works, it's very user-friendly, it has so many capabilities… Good stuff:
    - Waitlist for popular lots used to be done in person on the weekends, now in the system, implemented very well from the user perspective; informative for staff to see the data
    - Simple fact that it is self-serve; used to be a nightmare
    - Uploading proof of residency works well - if needed, goes into approval queue (they like the queue a lot, even if there are improvements that could be made)
- "For Passport, everything is a matter of time…If they had started two months in advance, these would not be issues." Started in October, October-December gathered reqs, December-March was focused on rolling out citations, that only left two months for intense development of permit system
- They are very capable with technology
- In retrospect should have tested with a pilot group before going live wtih 26k residents. 
- Our system was very unique and they ended up building a lot of Oak-Park-specific functionality; but so many edge cases covered it should be easy for whoever comes next
- If were rewriting contract, would ask for team of allocated staff to provide support to both city staff and residents

**Questions**

Joseph: Since your rollout, have you had to use the old system at all? 

- No. We didn't have the old system after three days. We might have used it to verify some things, but didn't really need it. We had to shut down vehicle permit before the Passport system was up and Passport implemented an interim solution using Google Sheets, then imported them to the new app; they were responsive. Now doing something similar for landlords while Passport builds that solution. 

Ryan: Will it ultimately be less work? 

- In the long run will really reduce workload, just a ton to work through now, people have problems renewing online and complain they have to come in - but still have 85% renewals online vs 65% previously

Ryan: How many staff do you have? 

- Three front desk, 1.5 solely answering phones, 3-6 full-time
- They do renewals 4 times a year (though are wondering if they recommend doing monthly if possible since so easy )

Ryan: Can you explain auto-renewal?

- Just like other renewals, can buy online and set up auto renew, automatically renews
- If you set up autorenewal there's no new verification you need to do. 

Joseph: What if people move? 

- We refund if people move, one more reason to move to monthly renewals. Also prorate.

Amenity: Do you think they just don't have QA?

- No, they do for big stuff, but they make lots of funcionality changes in the live app. They had a staging app up for us to test permits, but all the small changes they deploy now are done on the live app. 

Amenity: Have they made improvements based on customer usage and feedback? 

- Yes, a lot. For example people weren't finding a link, they updated it and created a pop up to help users. But honestly has been pretty usable; mostly non-tech-savvy users who were having issues. 

Amenity: How do residents determine eligibility?

- Initially asked for an address lookup that would bring up all of the nearest options. Has been on their wish list since the beginning. Currently just have info/tools for residents to look that up on their own site. 



Side convo: 

Use LDR for digital permitting - "It's pretty fantastic" Took setting up and getting used to; technology hurdle for officers; officer who was most resistent is now constant user

Reading of plates is phenomeal - can read bumper to bumper where not even a human could see
